import { type Knex } from 'knex';

/**
 * Migration: Configure aggressive autovacuum and autoanalyze thresholds
 * specifically for the high-activity 'products' table.
 *
 * This ensures that PostgreSQL aggressively reclaims dead row versions (bloat)
 * generated by frequent cashier delta inventory updates on stock_quantity.
 */
export async function up(knex: Knex): Promise<void> {
  const isPostgres = knex.client.driverName === 'pg' || 
                     knex.client.config.client === 'postgresql' || 
                     knex.client.config.client === 'pg';

  if (isPostgres) {
    await knex.raw(`
      ALTER TABLE products SET (
        autovacuum_vacuum_scale_factor = 0.05,
        autovacuum_analyze_scale_factor = 0.02
      );
    `);
  }
}

export async function down(knex: Knex): Promise<void> {
  const isPostgres = knex.client.driverName === 'pg' || 
                     knex.client.config.client === 'postgresql' || 
                     knex.client.config.client === 'pg';

  if (isPostgres) {
    await knex.raw(`
      ALTER TABLE products RESET (
        autovacuum_vacuum_scale_factor,
        autovacuum_analyze_scale_factor
      );
    `);
  }
}
